server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-dev.chj.cloud/eureka/

management.endpoints.web:
  exposure:
    include: "*"
    exclude: ""
